
services:
  fastapi:
    image: fastapi:latest
    ports:
      - 8000:8000
    # Uncomment the line below to run fastAPI in DEV mode.
    command: ["fastapi","dev", "main.py","--host" ,"0.0.0.0", "--port", "8000" ]
    volumes:
      - ./src:/app
  